name: Build and deploy ASP.Net Core app to Azure Web App - webappdemosponsotship

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build webapp-sam-lab13.csproj --configuration Release

      - name: Publish the application
        run: dotnet publish webapp-sam-lab13.csproj -c Release -o ./myapp
        # Assurez-vous que le chemin vers le fichier .csproj est correct

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8C54A0D57FB440C29AD6E2443A96E36C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7EF12F013DB046B582EFB5E260B26497 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_825DB8C19DE143FCAC96E469F117ABE2 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'webappdemosponsotship'
          slot-name: 'Production'
          package: ./myapp # Chemin vers le dossier publié
